# Generated by Django 5.1 on 2024-08-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('3Б', '3Б'), ('1Б', '1Б'), ('2А', '2А'), ('3А', '3А'), ('1А', '1А'), ('2Б', '2Б')], default='1А', max_length=2)),
                ('summer', models.CharField(choices=[('3Б', '3Б'), ('1Б', '1Б'), ('2А', '2А'), ('3А', '3А'), ('1А', '1А'), ('2Б', '2Б')], default='1А', max_length=2)),
                ('autumn', models.CharField(choices=[('3Б', '3Б'), ('1Б', '1Б'), ('2А', '2А'), ('3А', '3А'), ('1А', '1А'), ('2Б', '2Б')], default='1А', max_length=2)),
                ('spring', models.CharField(choices=[('3Б', '3Б'), ('1Б', '1Б'), ('2А', '2А'), ('3А', '3А'), ('1А', '1А'), ('2Б', '2Б')], default='1А', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(max_length=100)),
                ('connect', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('activities_types', models.CharField(choices=[('01', 'Пешком'), ('02', 'Лыжи'), ('03', 'Катамаран'), ('04', 'Байдарка'), ('05', 'Плот'), ('06', 'Cплав'), ('07', 'Велосипед'), ('08', 'Автомобиль'), ('09', 'Мотоцикл'), ('10', 'Парус'), ('11', 'верхом')], default='01', max_length=2)),
                ('status', models.CharField(choices=[('N', 'Новое'), ('P', 'В работе'), ('A', 'Принято'), ('R', 'Не принято')], default='N', max_length=1)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.coords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_img', models.CharField(max_length=100)),
                ('data', models.URLField(blank=True)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval_app.added')),
            ],
        ),
    ]
