# Generated by Django 5.1 on 2024-08-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval_app.added'),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('3А', '3А'), ('1Б', '1Б'), ('1А', '1А'), ('2Б', '2Б'), ('2А', '2А'), ('3Б', '3Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('3А', '3А'), ('1Б', '1Б'), ('1А', '1А'), ('2Б', '2Б'), ('2А', '2А'), ('3Б', '3Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('3А', '3А'), ('1Б', '1Б'), ('1А', '1А'), ('2Б', '2Б'), ('2А', '2А'), ('3Б', '3Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('3А', '3А'), ('1Б', '1Б'), ('1А', '1А'), ('2Б', '2Б'), ('2А', '2А'), ('3Б', '3Б')], default='1А', max_length=2),
        ),
    ]
