# Generated by Django 5.1 on 2024-08-31 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0002_alter_images_add_alter_level_autumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('2Б', '2Б'), ('3Б', '3Б'), ('1Б', '1Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('2Б', '2Б'), ('3Б', '3Б'), ('1Б', '1Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('2Б', '2Б'), ('3Б', '3Б'), ('1Б', '1Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('1А', '1А'), ('2А', '2А'), ('3А', '3А'), ('2Б', '2Б'), ('3Б', '3Б'), ('1Б', '1Б')], default='1А', max_length=2),
        ),
    ]
