# Generated by Django 5.1 on 2024-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0003_alter_added_add_time_alter_level_autumn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('3А', '3А'), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('3А', '3А'), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('3А', '3А'), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('3А', '3А'), ('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
