# Generated by Django 5.1 on 2024-09-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0004_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added',
            name='activities_types',
            field=models.CharField(choices=[('01', 'Пешком'), ('02', 'Лыжи'), ('03', 'Катамаран'), ('04', 'Байдарка'), ('05', 'Плот'), ('06', 'Cплав'), ('07', 'Велосипед'), ('08', 'Автомобиль'), ('09', 'Мотоцикл'), ('10', 'Парус'), ('11', 'Верхом')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('1А', '1А'), ('3Б', '3Б'), ('3А', '3А'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('1А', '1А'), ('3Б', '3Б'), ('3А', '3А'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('1А', '1А'), ('3Б', '3Б'), ('3А', '3А'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('1А', '1А'), ('3Б', '3Б'), ('3А', '3А'), ('2Б', '2Б')], default='1А', max_length=2),
        ),
    ]
